languageCode: en-us
baseURL: "https://keinli.netlify.app/"
title: Kein Li
paperSize: 5
# theme: PaperMod
theme:
  - PaperMod  # Replace "PaperMod" with your current theme name


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
relativeURL: true


minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kein Li
  description: "Kein Li website"
  keywords: [Blog, Portfolio, Data Science]
  author: Kein Li
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  assets:
    disableFingerprinting: true

  params:
    customCSS:
      - css/custom.css


  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShowShareButtons: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicons/favicon.ico"
    favicon16x16: "/favicons/favicon-16x16.png"
    favicon32x32: "/favicons/favicon-32x32.png"
    apple_touch_icon: "/favicons/apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Kein Li"
    icon: "images/coding.png"
    iconHeight: 35

  # profile-mode
  # profileMode:
  #   enabled: true # needs to be explicitly set
  #   title: "Hi, I'm Kein \U0001F680"
  #   subtitle: "Software Engineer Intern @ Syska Hennesey. Interested in iOS, Backend, and Databases"
  #   imageUrl: "images/profile.webp"
  #   imageWidth: 250
  #   imageHeight: 250
  #   buttons:
  #     - name: projects
  #       url: projects
  #     - name: resume
  #       url: resume

  markup:
    goldmark:
      renderer:
        unsafe: true

  # home-info mode
  homeInfoParams:
    # enabled: true
    Title: "Hi, I'm Kein \U0001F680"
    Content: |
      - Software Engineer Intern @ Syska Hennesey. Interested in Native iOS and Backend Development  
      - Currently
  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/keinli/"
    - name: github
      url: "https://github.com/kein-1"
    - name: cv
      url: "https://drive.google.com/file/d/1Z-bJVETagMPQDIQK5O_Tv2MCEcKaAj6e/view?usp=sharing"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    #   weight: 4
    # - identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
markup:
    goldmark:
        renderer:
            unsafe: true