languageCode: en-us
baseURL: "//chanin.tech/"
title: Kein Li
paginate: 5
# theme: PaperMod
theme:
  - hugo-embed-pdf-shortcode
  - PaperMod  # Replace "PaperMod" with your current theme name

enableInlineShortcodes: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Kein Li
  description: "Kein Li website"
  keywords: [Blog, Portfolio, Data Science]
  author: Kein Li
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  params:
    customCSS:
      - css/custom.css


  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  ShowShareButtons: false

  label:
    text: "Kein Li"
    icon: "images/coding.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hi, \U0001F44B I'm Kein"
    subtitle: "Currently a Software Engineer Intern @ Syska Hennesey"
    imageUrl: "images/profile.webp"
    imageWidth: 250
    imageHeight: 250
    buttons:
      - name: projects
        url: projects
      - name: resume
        url: resume

  markup:
    goldmark:
      renderer:
        unsafe: true

  # home-info mode
  homeInfoParams:
    # enabled: true
    Title: "Welcome! \U0001F44B"
    Content: "Kein li"

  socialIcons:
    
    - name: linkedin
      url: "https://www.linkedin.com/in/keinli/"
    - name: github
      url: "https://github.com/kein-1"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/chanin-www/content"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    - identifier: resume
      name: Resume
      url: /resume
      weight: 3
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 4
    
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai