name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3  
        with:
          hugo-version: 'latest'

      - name: Install themes
        run: git submodule update --init --recursive

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
